# Generated by Django 1.9.13 on 2017-12-16 23:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desiderata', '0003_auto_20171112_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiderataother',
            name='comment',
            field=models.TextField(default=b'', max_length=1000, verbose_name=b'uwagi'),
        ),
    ]
