# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desiderata', '0004_auto_20171216_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiderata',
            name='day',
            field=models.CharField(choices=[('1', 'poniedziałek'), ('2', 'wtorek'), ('3', 'środa'), ('4', 'czwartek'), ('5', 'piątek'), ('6', 'sobota'), ('7', 'niedziela')], max_length=1, verbose_name='dzień tygodnia'),
        ),
        migrations.AlterField(
            model_name='desiderata',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='prowadzący'),
        ),
        migrations.AlterField(
            model_name='desiderata',
            name='hour',
            field=models.IntegerField(verbose_name='godzina'),
        ),
        migrations.AlterField(
            model_name='desiderata',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester', verbose_name='semestr'),
        ),
        migrations.AlterField(
            model_name='desiderataother',
            name='comment',
            field=models.TextField(default='', max_length=1000, verbose_name='uwagi'),
        ),
        migrations.AlterField(
            model_name='desiderataother',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='prowadzący'),
        ),
        migrations.AlterField(
            model_name='desiderataother',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester', verbose_name='semestr'),
        ),
    ]
