# Generated by Django 3.0.6 on 2020-05-29 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200326_1613'),
        ('desiderata', '0005_auto_20180525_0559'),
    ]

    operations = [
        # Remove old entries.
        migrations.RunSQL(sql='''
            DELETE FROM
                desiderata_desiderata d
            USING
                desiderata_desiderata o
            WHERE
                d.employee_id = o.employee_id
                AND d.day = o.day
                AND d.hour = o.hour
                AND d.semester_id < o.semester_id
        '''),
        migrations.RunSQL(sql='''
            DELETE FROM
                desiderata_desiderataother d
            USING
                desiderata_desiderataother o
            WHERE
                d.employee_id = o.employee_id
                AND d.semester_id < o.semester_id
        '''),
        migrations.RemoveField(
            model_name='desiderata',
            name='semester',
        ),
        migrations.AlterField(
            model_name='desiderataother',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='inne uwagi'),
        ),
        migrations.AlterField(
            model_name='desiderataother',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='prowadzący'),
        ),
        migrations.AlterUniqueTogether(
            name='desiderataother',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='desiderataother',
            name='semester',
        ),
    ]
