# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_create', '0002_auto_20170529_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatekey',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll', verbose_name='ankieta'),
        ),
        migrations.AlterField(
            model_name='privatekey',
            name='private_key',
            field=models.TextField(verbose_name='klucz prywatny'),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll', verbose_name='ankieta'),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='public_key',
            field=models.TextField(verbose_name='klucz publiczny'),
        ),
        migrations.AlterField(
            model_name='studentgraded',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester', verbose_name='semestr'),
        ),
        migrations.AlterField(
            model_name='studentgraded',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='usedticketstamp',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll', verbose_name='ankieta'),
        ),
        migrations.AlterField(
            model_name='usedticketstamp',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='student'),
        ),
    ]
