# Generated by Django 2.1.15 on 2020-02-01 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20200129_1846'),
        ('ticket_create', '0003_auto_20180525_0559'),
        ('users', '0017_auto_20191020_1023'),
        ('courses', '0029_remove_term_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSAKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(verbose_name='klucz prywatny')),
                ('public_key', models.TextField(verbose_name='klucz publiczny')),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll', verbose_name='ankieta')),
            ],
            options={
                'verbose_name': 'klucze RSA',
                'verbose_name_plural': 'klucze RSA',
            },
        ),
        migrations.AlterModelOptions(
            name='studentgraded',
            options={'verbose_name': 'udział w ocenie', 'verbose_name_plural': 'udział w ocenie'},
        ),
        migrations.AlterUniqueTogether(
            name='studentgraded',
            unique_together={('student', 'semester')},
        ),
        migrations.RemoveField(
            model_name='privatekey',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='publickey',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='usedticketstamp',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='usedticketstamp',
            name='student',
        ),
        migrations.DeleteModel(
            name='PrivateKey',
        ),
        migrations.DeleteModel(
            name='PublicKey',
        ),
        migrations.DeleteModel(
            name='UsedTicketStamp',
        ),
    ]
