# Generated by Django 2.0.8 on 2019-03-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20180525_0559'),
        ('ticket_create', '0003_auto_20180525_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(verbose_name='klucz prywatny')),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll', verbose_name='ankieta')),
            ],
            options={
                'verbose_name': 'klucz prywatny',
                'verbose_name_plural': 'klucze prywatne',
            },
        ),
    ]
