# Generated by Django 2.0.8 on 2019-03-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_student_usos_id'),
        ('ticket_create', '0004_signingkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatekey',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='publickey',
            name='poll',
        ),
        migrations.AddField(
            model_name='signingkey',
            name='students',
            field=models.ManyToManyField(related_name='signingkeys', to='users.Student'),
        ),
        migrations.DeleteModel(
            name='PrivateKey',
        ),
        migrations.DeleteModel(
            name='PublicKey',
        ),
    ]
