# Generated by Django 2.0.8 on 2019-03-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_create', '0005_auto_20190323_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedticketstamp',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='usedticketstamp',
            name='student',
        ),
        migrations.DeleteModel(
            name='UsedTicketStamp',
        ),
    ]
