# Generated by Django 2.1.8 on 2019-05-05 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_create', '0006_auto_20190323_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signingkey',
            name='poll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll', verbose_name='ankieta'),
        ),
    ]
