# Generated by Django 2.1.8 on 2019-05-28 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20180525_0559'),
        ('courses', '0022_courseinstance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='course',
            new_name='old_course',
        ),
        migrations.AddField(
            model_name='event',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseInstance'),
        ),
        migrations.RunSQL(
            sql='''
                UPDATE schedule_event AS e
                SET course_id = ci.courseinformation_ptr_id
                FROM
                    courses_course AS c 
                    JOIN courses_courseinstance AS ci
                    ON (c.id=ci.old_course_id)
                WHERE c.id=e.old_course_id
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='event',
            name='old_course',
        )
    ]
