# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 17:27
from __future__ import unicode_literals

import apps.thesis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_auto_20180601_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('kind', models.SmallIntegerField(choices=[(apps.thesis.models.ThesisKind(0), 'mgr'), (apps.thesis.models.ThesisKind(1), 'inż'), (apps.thesis.models.ThesisKind(2), 'lic'), (apps.thesis.models.ThesisKind((3,)), 'lic+inż'), (apps.thesis.models.ThesisKind(4), 'isim')])),
                ('reserved', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thesis_advisor', to='users.Employee')),
                ('auxiliary_advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thesis_auxiliary_advisor', to='users.Employee')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thesis_student', to='users.Student')),
                ('student_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thesis_student_2', to='users.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisCommissionMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisSystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_required_votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ThesisVoteBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(apps.thesis.models.ThesisVote(1), 'brak głosu'), (apps.thesis.models.ThesisVote(2), 'odrzucona'), (apps.thesis.models.ThesisVote(3), 'zaakceptowana'), (apps.thesis.models.ThesisVote(4), 'brak użytkownika')])),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis.Thesis')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee')),
            ],
        ),
    ]
