# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-23 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesis',
            options={'verbose_name': 'Praca dyplomowa', 'verbose_name_plural': 'Prace dyplomowe'},
        ),
        migrations.AlterModelOptions(
            name='thesiscommissionmember',
            options={'verbose_name': 'Członek komisji', 'verbose_name_plural': 'Członkowie komisji'},
        ),
        migrations.AlterModelOptions(
            name='thesissystemsettings',
            options={'verbose_name_plural': 'Ustawienia systemu prac dyplomowych'},
        ),
    ]
