# Generated by Django 2.0.8 on 2018-12-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_to_group', models.BooleanField(default=True, verbose_name='Dodano do grupy')),
                ('add_new_group', models.BooleanField(default=True, verbose_name='Dodano nową grupe')),
                ('classroom_change', models.BooleanField(default=True, verbose_name='Zmieniono sale')),
            ],
        ),
    ]
