trigger:
- master-dev

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: kochanowski
  imageName: projektzapisy_base

steps:
- script:
    echo $(dockerHubTest)
- script: |
    echo $(localTest)
    docker login -u $(dockerId) -p "$(password)"
    #docker build -t $(dockerId)/$(imageName) -f Dockerfile.base .
    docker push $(dockerId)/$(imageName)
  env:
    password: $(dockerHubPassword)
    localTest: $(dockerHubTest)
