pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true

- bash: |
    git config --global user.email "$(gitUserEmail)"
    git config --global user.name "$(gitUserName)"
  displayName: Set identity

- bash: |
    git checkout $(zapisyRepositoryBranch)
    git remote add zapisy $(zapisyRepositoryURL)
    git pull zapisy $(zapisyRepositoryBranch)
  displayName: Pull latest changes

- bash: | 
    git status
    git remote -v
    git show-ref
    git push origin $(zapisyRepositoryBranch)
  displayName: Update the fork
