trigger:
- master-dev

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: kochanowski
  imageName: projektzapisy_base

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) -f Dockerfile.base .
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword)
