trigger:
- master-dev

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: kochanowski
  imageName: projektzapisy

steps:
- bash: |
    export UNVME_BASE=$(curl -s https://unversion.me/@kochanowski/projekt-zapisy/dockerhub/base/patch/)
    echo "##vso[task.setvariable variable=imageBaseVersion]$UNVME_BASE"
    export UNVME_DEVELOP=$(curl -s https://unversion.me/@kochanowski/projekt-zapisy/dockerhub/develop/patch/)
    echo "##vso[task.setvariable variable=imageDevelopVersion]$UNVME_DEVELOP"
    echo "Base version $UNVME_BASE"
    echo "Develop version $UNVME_DEVELOP"
  displayName: Get version numbers

- script: |
    echo "Building base image version $(imageBaseVersion)"
    docker login -u $(dockerId) -p $password
    docker build -t $(dockerId)/$(imageName):base -t $(dockerId)/$(imageName):base-$(imageBaseVersion) -f Dockerfile.base .
    # docker tag $(dockerId)/$(imageName):base $(dockerId)/$(imageName):base-$(imageBaseVersion)
    docker push $(dockerId)/$(imageName):base
    docker push $(dockerId)/$(imageName):base-$(imageBaseVersion) && curl -s https://unversion.me/listener/$(zapisyBaseListener)/$(imageBaseVersion)/
  env:
    password: $(dockerHubPassword)
  displayName: Push base image

- script: |
    echo "Building develop image version $(imageBaseVersion)"
    docker login -u $(dockerId) -p $password 
    docker build -t $(dockerId)/$(imageName):develop -t $(dockerId)/$(imageName):develop-$(imageDevelopVersion) -f Dockerfile .
    # docker tag $(dockerId)/$(imageName):develop $(dockerId)/$(imageName):develop-$(imageDevelopVersion)
    docker push $(dockerId)/$(imageName):develop
    docker push $(dockerId)/$(imageName):develop-$(imageDevelopVersion) && curl -s https://unversion.me/listener/$(zapisyDevelopListener)/$(imageDevelopVersion)/
  env:
    password: $(dockerHubPassword)
  displayName: Push develop image
