trigger:
- master-dev

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: kochanowski
  imageName: projektzapisy

steps:
- bash: |
    export UNVME_BASE=$(curl -s https://unversion.me/@kochanowski/projekt-zapisy/dockerhub/base/patch/)
    echo '##vso[task.setvariable variable=imageBaseVersion;isOutput=true]$UNVME_BASE'
    export UNVME_DEVELOP=$(curl -s https://unversion.me/@kochanowski/projekt-zapisy/dockerhub/develop/patch/)
    echo '##vso[task.setvariable variable=imageDevelopVersion;isOutput=true]$UNVME_DEVELOP'
    echo "Base version $UNVME_BASE"
    echo "Develop version $UNVEM_DEVELOP"
  name: setVersions
  displayName: Get version numbers

- script: |
    docker login -u $(dockerId) -p $password
    docker build -t $(dockerId)/$(imageName):base -t $(dockerId)/$(imageName):base-$(setVersions.imageBaseVersion) -f Dockerfile.base .
    docker push $(dockerId)/$(imageName):base-$(setVersions.imageBaseVersion) && curl -s https://unversion.me/listener/$(zapisyBaseListener)/$(setVersions.imageBaseVersion)/
  env:
    password: $(dockerHubPassword)
  displayName: Push base image

- script: |
    docker login -u $(dockerId) -p $password 
    docker build -t $(dockerId)/$(imageName):develop -t $(dockerId)/$(imageName):develop-$(setVersions.imageDevelopVersion) -f Dockerfile .
    docker push $(dockerId)/$(imageName):develop-$(setVersions.imageDevelopVersion) && curl -s https://unversion.me/listener/$(zapisyDevelopListener)/$(setVersions.imageDevelopVersion)/
  env:
    password: $(dockerHubPassword)
  displayName: Push develop image
