version: "2"
services:
  postgresdb:
    image: postgres:11.2
    restart: always
    environment:
      - POSTGRES_USER=fereol
      - POSTGRES_PASSWORD=fereolpass
      - POSTGRES_DB=fereol
    ports:
      - "5432:5432"
    volumes:
      - ./zapisy:/vagrant/zapisy
      - zapisy_pgdata:/var/lib/postgresql/data
  
  projektzapisy:
    container_name: projektzapisy
    build:
      context: .
      dockerfile: Dockerfile
    command: pipenv run python run.py server
    image: kochanowski/projektzapisy:latest
    stdin_open: true
    tty: true
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    volumes:
      - ./zapisy:/vagrant/zapisy
      - zapisy_node_modules:/vagrant_node_modules
    ports:
      - "80:8001"
      - "8000:8000"
    depends_on: 
      - postgresdb
    # network_mode: "host"

volumes:
  zapisy_pgdata:
  zapisy_node_modules: