# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-16 17:54
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20171112_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'number', unique_with=(b'number',)),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='type',
            field=models.IntegerField(choices=[(0, 'Sala wyk\u0142adowa'), (1, 'Sala \u0107wiczeniowa'), (2, 'Pracownia komputerowa - Windows'), (3, 'Pracownia komputerowa - Linux'), (4, 'Pracownia dwusystemowa (Windows+Linux)'), (5, 'Poligon (109)')], default=1, verbose_name=b'typ'),
        ),
    ]
