# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-23 11:45
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20171112_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'number', unique_with=(b'number',)),
        ),
    ]
