# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models


def group_copy_teacher_to_teachers(apps, _schema_editor):
    Group = apps.get_model('courses', 'Group')
    for group in Group.objects.all():
        tchr = group.teacher
        if tchr is None:
            continue
        group.teachers.add(tchr)
        group.save()


class Migration(migrations.Migration):
    """The migration handles adding the teachers field to enrollment.course.Group model"""
    dependencies = [
        ('users', '0005_auto_20171019_1044'),
        ('courses', '0006_auto_20171216_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(
                related_name='taught_groups',
                to='users.Employee',
                verbose_name=b'prowadzący'),
        ),
        migrations.RunPython(group_copy_teacher_to_teachers),
    ]
