# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20171216_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedday',
            name='day',
            field=models.DateField(unique=True, verbose_name='dzień wolny'),
        ),
        migrations.AlterField(
            model_name='changedday',
            name='weekday',
            field=models.CharField(choices=[('1', 'poniedziałek'), ('2', 'wtorek'), ('3', 'środa'), ('4', 'czwartek'), ('5', 'piątek'), ('6', 'sobota'), ('7', 'niedziela')], max_length=1, verbose_name='zmieniony na'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='building',
            field=models.CharField(blank=True, default='', max_length=75, verbose_name='budynek'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='liczba miejsc'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(0, 'Parter'), (1, 'I piętro'), (2, 'II Piętro'), (3, 'III piętro')], null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='number',
            field=models.CharField(max_length=20, verbose_name='numer sali'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='number'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='type',
            field=models.IntegerField(choices=[(0, 'Sala wykładowa'), (1, 'Sala ćwiczeniowa'), (2, 'Pracownia komputerowa - Windows'), (3, 'Pracownia komputerowa - Linux'), (4, 'Pracownia dwusystemowa (Windows+Linux)'), (5, 'Poligon (109)')], default=1, verbose_name='typ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='english',
            field=models.BooleanField(default=False, verbose_name='przedmiot prowadzony w j.angielskim'),
        ),
        migrations.AlterField(
            model_name='course',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseEntity', verbose_name='podstawa przedmiotu'),
        ),
        migrations.AlterField(
            model_name='course',
            name='information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseDescription', verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='course',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='uwagi do tej edyci przedmiotu'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Semester', verbose_name='semestr'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='odnośnik'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_options',
            field=models.ManyToManyField(through='courses.StudentOptions', to='users.Student', verbose_name='opcje studentów'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='users.Employee', verbose_name='prowadzący'),
        ),
        migrations.AlterField(
            model_name='course',
            name='web_page',
            field=models.URLField(blank=True, null=True, verbose_name='Strona WWW przedmiotu'),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='description_pl',
            field=models.TextField(blank=True, default='', null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='exam',
            field=models.BooleanField(default=False, verbose_name='egzamin'),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='_coursedescription_requirements_+', to='courses.CourseEntity', verbose_name='wymagania'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Utworzono'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='ukryty'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Ostatnia zmiana'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='english',
            field=models.BooleanField(default=False, verbose_name='przedmiot prowadzony w j.angielskim'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='exam',
            field=models.BooleanField(default=True, verbose_name='egzamin'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='in_prefs',
            field=models.BooleanField(default=True, verbose_name='w preferencjach'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='name_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='opiekun'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='semester',
            field=models.CharField(choices=[('u', 'nieoznaczony'), ('z', 'zimowy'), ('l', 'letni')], default='u', max_length=1, verbose_name='semestr'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='shortName',
            field=models.CharField(blank=True, help_text='Opcjonalna skrócona nazwa, używana na np. planie. Przykłady: JFiZO, AiSD', max_length=30, null=True, verbose_name='skrócona nazwa'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='odnośnik (nazwa pojawiająca się w urlach)'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='suggested_for_first_year',
            field=models.BooleanField(default=False, verbose_name='polecany dla pierwszego roku'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Type', verbose_name='rodzaj'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='usos_kod',
            field=models.CharField(blank=True, default='', help_text='UWAGA! Nie edytuj tego pola sam!', max_length=20, null=True, verbose_name='Kod przedmiotu w usos'),
        ),
        migrations.AlterField(
            model_name='courseentity',
            name='web_page',
            field=models.URLField(blank=True, null=True, verbose_name='strona www'),
        ),
        migrations.AlterField(
            model_name='freeday',
            name='day',
            field=models.DateField(unique=True, verbose_name='dzień wolny'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.Course', verbose_name='przedmiot'),
        ),
        migrations.AlterField(
            model_name='group',
            name='enrolled',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='liczba zapisanych studentów'),
        ),
        migrations.AlterField(
            model_name='group',
            name='enrolled_isim',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='liczba zapisanych studentów ISIM'),
        ),
        migrations.AlterField(
            model_name='group',
            name='enrolled_zam',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='liczba zapisanych studentów zamawianych'),
        ),
        migrations.AlterField(
            model_name='group',
            name='enrolled_zam2012',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='liczba zapisanych studentów zamawianych'),
        ),
        migrations.AlterField(
            model_name='group',
            name='export_usos',
            field=models.BooleanField(default=True, verbose_name='czy eksportować do usos?'),
        ),
        migrations.AlterField(
            model_name='group',
            name='extra',
            field=models.CharField(blank=True, choices=[('', ''), ('pierwsze 7 tygodni', 'pierwsze 7 tygodni'), ('drugie 7 tygodni', 'drugie 7 tygodni'), ('grupa rezerwowa', 'grupa rezerwowa'), ('grupa licencjacka', 'grupa licencjacka'), ('grupa magisterska', 'grupa magisterska'), ('grupa zaawansowana', 'grupa zaawansowana'), ('zajecia na mat.', 'zajęcia na matematyce'), ('wykład okrojony', 'wykład okrojony'), ('grupa 1', 'grupa 1'), ('grupa 2', 'grupa 2'), ('grupa 3', 'grupa 3'), ('grupa 4', 'grupa 4'), ('grupa 5', 'grupa 5'), ('pracownia linuksowa', 'pracownia linuksowa'), ('grupa anglojęzyczna', 'grupa anglojęzyczna'), ('I rok', 'I rok'), ('II rok', 'II rok'), ('ISIM', 'ISIM')], default='', max_length=20, verbose_name='dodatkowe informacje'),
        ),
        migrations.AlterField(
            model_name='group',
            name='limit',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='limit miejsc'),
        ),
        migrations.AlterField(
            model_name='group',
            name='limit_isim',
            field=models.PositiveSmallIntegerField(default=0, help_text='miejsca gwarantowane dla studentów isim', verbose_name='miejsca dla ISIM'),
        ),
        migrations.AlterField(
            model_name='group',
            name='limit_zamawiane',
            field=models.PositiveSmallIntegerField(default=0, help_text='miejsca gwarantowane dla studentów zamawianych 2009', verbose_name='miejsca dla zamawianych 2009'),
        ),
        migrations.AlterField(
            model_name='group',
            name='limit_zamawiane2012',
            field=models.PositiveSmallIntegerField(default=0, help_text='miejsca gwarantowane dla studentów zamawianych 2012', verbose_name='miejsca dla zamawianych 2012'),
        ),
        migrations.AlterField(
            model_name='group',
            name='queued',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='liczba studentów w kolejce'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='prowadzący'),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('1', 'wykład'), ('2', 'ćwiczenia'), ('3', 'pracownia'), ('5', 'ćwiczenio-pracownia'), ('6', 'seminarium'), ('7', 'lektorat'), ('8', 'WF'), ('9', 'repetytorium'), ('10', 'projekt')], max_length=2, verbose_name='typ zajęć'),
        ),
        migrations.AlterField(
            model_name='group',
            name='usos_nr',
            field=models.IntegerField(blank=True, help_text='UWAGA! Nie edytuj tego pola sam!', null=True, verbose_name='Nr grupy w usos'),
        ),
        migrations.AlterField(
            model_name='pointsofcourseentities',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseEntity', verbose_name='podstawa przedmiotu'),
        ),
        migrations.AlterField(
            model_name='pointsofcourseentities',
            name='program',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Program', verbose_name='Program Studiów'),
        ),
        migrations.AlterField(
            model_name='pointsofcourseentities',
            name='type_of_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.PointTypes', verbose_name='rodzaj punktów'),
        ),
        migrations.AlterField(
            model_name='pointsofcourseentities',
            name='value',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='liczba punktów'),
        ),
        migrations.AlterField(
            model_name='pointtypes',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='rodzaj punktów'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='desiderata_closing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas zamknięcia dezyderat'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='desiderata_opening',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas otwarcia dezyderat'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='first_grade_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fgrade', to='courses.Semester', verbose_name='Pierwszy semestr oceny'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='is_grade_active',
            field=models.BooleanField(default=False, verbose_name='Ocena aktywna'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='lectures_beginning',
            field=models.DateField(blank=True, null=True, verbose_name='Dzień rozpoczęcia zajęć'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='lectures_ending',
            field=models.DateField(blank=True, null=True, verbose_name='Dzień zakończenia zajęć'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='records_closing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas zamkniecia zapisów'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='records_ects_limit_abolition',
            field=models.DateTimeField(null=True, verbose_name='Czas zniesienia limitu 35 ECTS'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='records_ending',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas zamknięcia wypisów'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='records_opening',
            field=models.DateTimeField(blank=True, help_text='Godzina powinna być ustawiona na 00:00:00, by studenci mieli otwarcie między 10:00 a 22:00.', null=True, verbose_name='Czas otwarcia zapisów'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='second_grade_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sgrade', to='courses.Semester', verbose_name='Drugi semester oceny'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_beginning',
            field=models.DateField(verbose_name='Data rozpoczęcia semestru'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_ending',
            field=models.DateField(verbose_name='Data zakończenia semestru'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='type',
            field=models.CharField(choices=[('z', 'zimowy'), ('l', 'letni')], max_length=1, verbose_name='rodzaj semestru'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='widoczny'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.CharField(default='0', max_length=7, verbose_name='rok akademicki'),
        ),
        migrations.AlterField(
            model_name='studentoptions',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='przedmiot'),
        ),
        migrations.AlterField(
            model_name='studentoptions',
            name='records_opening_bonus_minutes',
            field=models.IntegerField(default=0, verbose_name='Przyspieszenie otwarcia zapisów na ten przedmiot (minuty)'),
        ),
        migrations.AlterField(
            model_name='studentoptions',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='term',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Classroom', verbose_name='sala'),
        ),
        migrations.AlterField(
            model_name='term',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='new_classrooms', to='courses.Classroom', verbose_name='sale'),
        ),
        migrations.AlterField(
            model_name='term',
            name='dayOfWeek',
            field=models.CharField(choices=[('1', 'poniedziałek'), ('2', 'wtorek'), ('3', 'środa'), ('4', 'czwartek'), ('5', 'piątek'), ('6', 'sobota'), ('7', 'niedziela')], max_length=1, verbose_name='dzień tygodnia'),
        ),
        migrations.AlterField(
            model_name='term',
            name='end_time',
            field=models.TimeField(verbose_name='zakończenie'),
        ),
        migrations.AlterField(
            model_name='term',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term', to='courses.Group', verbose_name='grupa'),
        ),
        migrations.AlterField(
            model_name='term',
            name='start_time',
            field=models.TimeField(verbose_name='rozpoczęcie'),
        ),
        migrations.AlterField(
            model_name='type',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Type', verbose_name='grupa'),
        ),
        migrations.AlterField(
            model_name='type',
            name='meta_type',
            field=models.BooleanField(default=False, verbose_name='Grupa typow'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='rodzaj zajec'),
        ),
        migrations.AlterField(
            model_name='type',
            name='short_name',
            field=models.CharField(default='', max_length=5, verbose_name='rodzaj zajec (króŧka forma)'),
        ),
    ]
