# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-29 22:28
from __future__ import unicode_literals

from django.db import migrations, models

def copy_first_of_teachers(apps, schema_editor):
    """If single Teacher replaces ManyToManyRelation teachers, we need to pick
    one of the teachers in the group to be the one. We are picking the first
    one."""
    Group = apps.get_model('courses', 'Group')
    for group in Group.objects.all():
        teachers = list(group.teachers.all())
        if not teachers:
            continue
        group.teacher = teachers[0]
        group.save()

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_group_teachers'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_code=copy_first_of_teachers),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(related_name='taught_groups',
                                         to='users.Employee',
                                         verbose_name=b'nauczyciele'),
        ),
    ]
