# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-09 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180602_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='enrolled_zam',
        ),
        migrations.RemoveField(
            model_name='group',
            name='enrolled_zam2012',
        ),
        migrations.RemoveField(
            model_name='group',
            name='limit_zamawiane',
        ),
        migrations.RemoveField(
            model_name='group',
            name='limit_zamawiane2012',
        ),
    ]
