# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180525_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseentity',
            name='in_prefs',
            field=models.BooleanField(default=False, verbose_name='w preferencjach'),
        ),
    ]
