# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-12 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180525_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='enrolled_zam',
        ),
        migrations.RemoveField(
            model_name='group',
            name='enrolled_zam2012',
        ),
        migrations.RemoveField(
            model_name='group',
            name='limit_zamawiane',
        ),
        migrations.RemoveField(
            model_name='group',
            name='limit_zamawiane2012',
        ),
    ]
