# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-21 21:42
from __future__ import unicode_literals

from django.db import migrations, models


def move_teacher_to_teachers(apps, schema_editor):
    Group = apps.get_model('courses', 'Group')

    for group in Group.objects.all():
        if group.teacher:
            group.teachers.add(group.teacher)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180712_1227'),
        ('courses', '0009_auto_20180712_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='_group_teachers_+', to='users.Employee', verbose_name='lista prowadzących'),
        ),
        migrations.RunPython(move_teacher_to_teachers),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='users.Employee', verbose_name='lista prowadzących'),
        ),
    ]
