# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-12 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_group_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='users.Employee', verbose_name='lista prowadzących'),
        ),
    ]
