# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-09 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180712_1227'),
        ('courses', '0011_remove_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='prowadzący'),
        ),
    ]
