# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-07 12:49
from __future__ import unicode_literals

from django.db import migrations

def make_many_teachers(apps, schema_editor):
    Group = apps.get_model('courses', 'Group')

    for group in Group.objects.all():
        if group.owner:
            group.teachers.add(group.teacher)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_group_teachers'),
    ]

    operations = [
        migrations.RunPython(make_many_teachers),
    ]
