# Generated by Django 2.0.8 on 2019-01-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_manual_remove_pointsview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='extra',
            field=models.CharField(blank=True, choices=[('', ''), ('pierwsze 7 tygodni', 'pierwsze 7 tygodni'), ('drugie 7 tygodni', 'drugie 7 tygodni'), ('grupa rezerwowa', 'grupa rezerwowa'), ('grupa licencjacka', 'grupa licencjacka'), ('grupa magisterska', 'grupa magisterska'), ('grupa zaawansowana', 'grupa zaawansowana'), ('zajecia na mat.', 'zajęcia na matematyce'), ('wykład okrojony', 'wykład okrojony'), ('grupa 1', 'grupa 1'), ('grupa 2', 'grupa 2'), ('grupa 3', 'grupa 3'), ('grupa 4', 'grupa 4'), ('grupa 5', 'grupa 5'), ('pracownia linuksowa', 'pracownia linuksowa'), ('grupa anglojęzyczna', 'grupa anglojęzyczna'), ('I rok', 'I rok'), ('II rok', 'II rok'), ('ISIM', 'ISIM'), ('tura1', 'grupa wirtualna dla pierwszej 1/3 pierwszaków'), ('tura2', 'grupa wirtualna dla drugiej 1/3 pierwszaków'), ('tura3', 'grupa wirtualna dla trzeciej 1/3 pierwszaków')], default='', max_length=20, verbose_name='dodatkowe informacje'),
        ),
    ]
