# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-16 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20181107_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='_group_teachers_+', to='users.Employee', verbose_name='lista prowadzących'),
        ),
    ]
