# Generated by Django 2.0.8 on 2019-03-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20190212_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='usos_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID sali w systemie USOS'),
        ),
        migrations.AddField(
            model_name='semester',
            name='usos_kod',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Kod semestru w systemie USOS'),
        ),
        migrations.AddField(
            model_name='term',
            name='usos_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Kod terminu w systemie USOS'),
        ),
    ]
