# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-09 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_group_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
    ]
