# Generated by Django 2.0.8 on 2019-03-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20190312_1330'),
        ('courses', '0015_remove_course_teachers'),
    ]

    operations = [
    ]
