# Generated by Django 2.1.8 on 2019-05-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_courseinformation_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinformation',
            name='hours_exercise',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='godzin ćwiczeń'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='hours_exercise_lab',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='godzin ćwiczenio-pracowni'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='hours_lab',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='godzin pracowni'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='hours_lecture',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='godzin wykładu'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='hours_recap',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='godzin repetytorium'),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='hours_seminar',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='godzin seminarium'),
        ),
    ]
