# Generated by Django 2.1.8 on 2019-07-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20190508_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('1', 'wykład'), ('2', 'ćwiczenia'), ('3', 'pracownia'), ('5', 'ćwiczenio-pracownia'), ('6', 'seminarium'), ('7', 'lektorat'), ('8', 'WF'), ('9', 'repetytorium'), ('10', 'projekt'), ('11', 'tutoring'), ('12', 'proseminarium')], max_length=2, verbose_name='typ zajęć'),
        ),
    ]
