# Generated by Django 2.1.8 on 2019-05-17 16:37

from django.db import migrations, models


def copy_points(apps, schema_editor):
    PointsOfCourseEntities = apps.get_model('courses', 'PointsOfCourseEntities')
    pocs = PointsOfCourseEntities.objects.filter(program__isnull=True).exclude(
        entity__courseinformation__isnull=True)
    for poc in pocs:
        poc.entity.courseinformation.points = poc.value
        poc.entity.courseinformation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_program_type_of_points'),
        ('courses', '0020_auto_20190721_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinformation',
            name='points',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='ECTS'),
        ),
        migrations.RunPython(
            code=copy_points,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='pointsofcourseentities',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='pointsofcourseentities',
            name='program',
        ),
        migrations.RemoveField(
            model_name='pointsofcourseentities',
            name='type_of_point',
        ),
        migrations.DeleteModel(
            name='PointsOfCourseEntities',
        ),
        migrations.DeleteModel(
            name='PointTypes',
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS courses_studentpointsview;',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
