# Generated by Django 2.1.8 on 2019-05-24 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_courseinstance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='course',
            new_name='old_course',
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, null=True, related_name='groups', to='courses.CourseInstance', verbose_name='przedmiot'),
        ),
        migrations.RunSQL(
            sql='''UPDATE courses_group AS g
                SET course_id = ci.courseinformation_ptr_id
                FROM
                    courses_course AS c 
                    JOIN courses_courseinstance AS ci
                    ON (c.id=ci.old_course_id)
                WHERE c.id=g.old_course_id
                ''',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='group',
            name='old_course',
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.CourseInstance', verbose_name='przedmiot'),
        ),
    ]
