# Generated by Django 2.1.8 on 2019-06-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20190524_2044'),
        ('proposal', '0008_auto_20190528_1403'),
        ('vote', '0005_remove_singlevote_entity'),
        ('schedule', '0007_auto_20190528_0101'),
        ('preferences', '0005_auto_20190511_1814'),
        ('poll', '0007_auto_20190529_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='course',
            name='information',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students_options',
        ),
        migrations.RemoveField(
            model_name='coursedescription',
            name='author',
        ),
        migrations.RemoveField(
            model_name='coursedescription',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='coursedescription',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='courseentity',
            name='effects',
        ),
        migrations.RemoveField(
            model_name='courseentity',
            name='information',
        ),
        migrations.RemoveField(
            model_name='courseentity',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='courseentity',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='courseentity',
            name='type',
        ),
        migrations.AlterUniqueTogether(
            name='studentoptions',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='studentoptions',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentoptions',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tagcourseentity',
            name='courseentity',
        ),
        migrations.RemoveField(
            model_name='tagcourseentity',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='courseinformation',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='courseinstance',
            name='old_course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseDescription',
        ),
        migrations.DeleteModel(
            name='CourseEntity',
        ),
        migrations.DeleteModel(
            name='StudentOptions',
        ),
        migrations.DeleteModel(
            name='TagCourseEntity',
        ),
    ]
