# Generated by Django 2.1.8 on 2019-06-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20190603_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='obligatory',
            field=models.BooleanField(default=False, verbose_name='przedmioty obowiązkowe'),
        ),
        migrations.RunSQL(
            sql='''UPDATE courses_type SET obligatory=True WHERE short_name ILIKE 'O%';''',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
