# Generated by Django 2.1.9 on 2019-08-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('courses', '0027_auto_20190822_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuaranteedSpots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveSmallIntegerField(verbose_name='liczba miejsc')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guaranteed_spots', to='courses.Group', verbose_name='grupa zajęciowa')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.Group', verbose_name='grupa użytkowników')),
            ],
            options={'verbose_name': 'miejsca gwarantowane', 'verbose_name_plural': 'miejsca gwarantowane'},
        ),
    ]
