# Generated by Django 2.1.14 on 2019-11-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_guaranteedspots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='classroom',
        ),
    ]
