# Generated by Django 3.0.5 on 2020-04-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_remove_term_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(0, 'Parter'), (1, 'I piętro'), (2, 'II piętro'), (3, 'III piętro')], null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='extra',
            field=models.CharField(blank=True, choices=[('', ''), ('pierwsze 7 tygodni', 'pierwsze 7 tygodni'), ('drugie 7 tygodni', 'drugie 7 tygodni'), ('grupa rezerwowa', 'grupa rezerwowa'), ('grupa licencjacka', 'grupa licencjacka'), ('grupa magisterska', 'grupa magisterska'), ('grupa zaawansowana', 'grupa zaawansowana'), ('zajęcia na mat.', 'zajęcia na matematyce'), ('wykład okrojony', 'wykład okrojony'), ('grupa 1', 'grupa 1'), ('grupa 2', 'grupa 2'), ('grupa 3', 'grupa 3'), ('grupa 4', 'grupa 4'), ('grupa 5', 'grupa 5'), ('pracownia linuksowa', 'pracownia linuksowa'), ('grupa anglojęzyczna', 'grupa anglojęzyczna'), ('I rok', 'I rok'), ('II rok', 'II rok'), ('ISIM', 'ISIM'), ('hidden', 'grupa ukryta')], default='', max_length=20, verbose_name='dodatkowe informacje'),
        ),
        migrations.DeleteModel(
            name='StudentPointsView',
        ),
    ]
