# Generated by Django 3.0.6 on 2020-05-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_auto_20200420_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='desiderata_closing',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='desiderata_opening',
        ),
    ]
