# Generated by Django 3.0.10 on 2020-09-08 12:40

from django.db import migrations, models


def migrate_labels(apps, schema_editor):
    migrations_map = {
        'pierwsze 7 tygodni': 'Q1',
        'drugie 7 tygodni': 'Q2',
        'grupa zaawansowana': 'zaaw',
        'zajęcia na mat.': 'mat',
        'grupa anglojęzyczna': 'english',
    }
    Group = apps.get_model('courses', 'Group')
    updates = []
    for group in Group.objects.filter(extra__in=migrations_map.keys()):
        group.extra = migrations_map.get(group.extra)
        updates.append(group)
    Group.objects.bulk_update(updates, fields=['extra'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20200529_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='extra',
            field=models.CharField(blank=True, default='', help_text="Można wpisywać tagi oddzielone przecinkami. Zostaną one wyświetlone na stronie przedmiotu. Nie ma żadnych dozwolonych tagów, ale dla wybranych tagów zostanie dodany tooltip z wyjaśnieniem: {'Q1': 'pierwsze 7 tygodni', 'Q2': 'drugie 7 tygodni', 'zaaw': 'grupa zaawansowana', 'mat': 'zajęcia na matematyce', 'eng': 'grupa anglojęzyczna', 'zdalna': 'zajęcia prowadzone zdalnie'}", max_length=255, verbose_name='dodatkowe informacje'),
        ),
        migrations.RunPython(migrate_labels),
    ]
