# Generated by Django 3.0.10 on 2020-09-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20200908_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='auto_enrollment',
            field=models.BooleanField(default=False, help_text='Blokuje zapisywanie do grupy. Zamiast tego, studenci są do niej automatycznie zapisani jeśli zapiszą się\xa0do jakiejkolwiek innej grupy z tego przedmiotu. Nie należy blokować\xa0wszystkich grup z przedmiotu ani grup, gdzie studenci powinni mieć wybór (np. jest kilka równoległych grup ćwiczeniowych).', verbose_name='grupa z auto-zapisem'),
        ),
    ]
