# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('-', 'Hidden'), ('offer', 'Oferta'), ('enrollment', 'Zapisy'), ('grade', 'Ocena zajęć')], default='-', max_length=15, verbose_name='Kategoria'),
        ),
    ]
