# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20170606_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='choice_limit',
            field=models.IntegerField(verbose_name='maksimum opcji do wyboru'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='content',
            field=models.CharField(max_length=250, verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='has_other',
            field=models.BooleanField(default=False, verbose_name='opcja inne'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='options',
            field=models.ManyToManyField(to='poll.Option', verbose_name='odpowiedzi'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='sections',
            field=models.ManyToManyField(through='poll.MultipleChoiceQuestionOrdering', to='poll.Section', verbose_name='sekcje'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestionanswer',
            name='options',
            field=models.ManyToManyField(blank=True, to='poll.Option', verbose_name='odpowiedzi'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestionanswer',
            name='other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='inne'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.MultipleChoiceQuestion', verbose_name='pytanie'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestionanswer',
            name='saved_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.SavedTicket', verbose_name='zapisany bilet'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestionanswer',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Section', verbose_name='sekcja'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestionordering',
            name='position',
            field=models.IntegerField(verbose_name='pozycja'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestionordering',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.MultipleChoiceQuestion', verbose_name='pytanie'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestionordering',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Section', verbose_name='sekcja'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='content',
            field=models.CharField(max_length=250, verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='sections',
            field=models.ManyToManyField(through='poll.OpenQuestionOrdering', to='poll.Section', verbose_name='sekcje'),
        ),
        migrations.AlterField(
            model_name='openquestionanswer',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='openquestionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.OpenQuestion', verbose_name='pytanie'),
        ),
        migrations.AlterField(
            model_name='openquestionanswer',
            name='saved_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.SavedTicket', verbose_name='zapisany bilet'),
        ),
        migrations.AlterField(
            model_name='openquestionanswer',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Section', verbose_name='sekcja'),
        ),
        migrations.AlterField(
            model_name='openquestionordering',
            name='position',
            field=models.IntegerField(verbose_name='pozycja'),
        ),
        migrations.AlterField(
            model_name='openquestionordering',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.OpenQuestion', verbose_name='pytanie'),
        ),
        migrations.AlterField(
            model_name='openquestionordering',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Section', verbose_name='sekcja'),
        ),
        migrations.AlterField(
            model_name='option',
            name='content',
            field=models.CharField(max_length=250, verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='users.Employee', verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='usunięta'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='zakończona'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Group', verbose_name='grupa'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='origin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.Origin', verbose_name='zbiór'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester', verbose_name='semestr'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='share_result',
            field=models.BooleanField(default=False, verbose_name='udostępnij wyniki'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='studies_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Program', verbose_name='typ studiów'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=40, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='savedticket',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='czy zakończona'),
        ),
        migrations.AlterField(
            model_name='savedticket',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll', verbose_name='ankieta'),
        ),
        migrations.AlterField(
            model_name='savedticket',
            name='ticket',
            field=models.TextField(verbose_name='bilet'),
        ),
        migrations.AlterField(
            model_name='section',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='usunięta'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='section',
            name='poll',
            field=models.ManyToManyField(through='poll.SectionOrdering', to='poll.Poll', verbose_name='ankieta'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=50, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='sectionordering',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Poll', verbose_name='ankieta'),
        ),
        migrations.AlterField(
            model_name='sectionordering',
            name='position',
            field=models.IntegerField(verbose_name='pozycja'),
        ),
        migrations.AlterField(
            model_name='sectionordering',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Section', verbose_name='sekcja'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='content',
            field=models.CharField(max_length=250, verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='is_scale',
            field=models.BooleanField(default=False, verbose_name='skala'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='options',
            field=models.ManyToManyField(to='poll.Option', verbose_name='odpowiedzi'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='sections',
            field=models.ManyToManyField(through='poll.SingleChoiceQuestionOrdering', to='poll.Section', verbose_name='sekcje'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestionanswer',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.Option', verbose_name='odpowiedź'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.SingleChoiceQuestion', verbose_name='pytanie'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestionanswer',
            name='saved_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.SavedTicket', verbose_name='zapisany bilet'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestionanswer',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Section', verbose_name='sekcja'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestionordering',
            name='hide_on',
            field=models.ManyToManyField(blank=True, to='poll.Option', verbose_name='ukryj sekcję przy                                                          odpowiedziach'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestionordering',
            name='is_leading',
            field=models.BooleanField(default=False, verbose_name='pytanie wiodące'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestionordering',
            name='position',
            field=models.IntegerField(verbose_name='pozycja'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestionordering',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.SingleChoiceQuestion', verbose_name='pytanie'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestionordering',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Section', verbose_name='sekcja'),
        ),
        migrations.AlterField(
            model_name='template',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='template',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseEntity', verbose_name='przedmiot'),
        ),
        migrations.AlterField(
            model_name='template',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='usunięty'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='template',
            name='exam',
            field=models.BooleanField(default=True, verbose_name='przedmiot z egzaminem'),
        ),
        migrations.AlterField(
            model_name='template',
            name='group_type',
            field=models.CharField(blank=True, choices=[('1', 'wykład'), ('2', 'ćwiczenia'), ('3', 'pracownia'), ('5', 'ćwiczenio-pracownia'), ('6', 'seminarium'), ('7', 'lektorat'), ('8', 'WF'), ('9', 'repetytorium'), ('10', 'projekt')], max_length=2, null=True, verbose_name='typ zajęć'),
        ),
        migrations.AlterField(
            model_name='template',
            name='no_course',
            field=models.BooleanField(default=False, verbose_name='nie przypisany'),
        ),
        migrations.AlterField(
            model_name='template',
            name='sections',
            field=models.ManyToManyField(through='poll.TemplateSections', to='poll.Section', verbose_name='sekcje'),
        ),
        migrations.AlterField(
            model_name='template',
            name='studies_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Program', verbose_name='typ studiów'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=40, verbose_name='tytuł'),
        ),
        migrations.AlterField(
            model_name='templatesections',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Section', verbose_name='sekcja'),
        ),
        migrations.AlterField(
            model_name='templatesections',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Template', verbose_name='ankieta'),
        ),
    ]
