# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-29 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20180525_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='savedticket',
            name='finished',
        ),
    ]
