# Generated by Django 2.1.8 on 2019-05-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20180525_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='share_result',
            field=models.BooleanField(blank=True, default=False, verbose_name='udostępnij wyniki'),
        ),
    ]
