# Generated by Django 2.1.8 on 2019-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20190804_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='course',
        ),
        migrations.AlterField(
            model_name='poll',
            name='share_result',
            field=models.BooleanField(blank=True, default=False, verbose_name='udostępnij wyniki'),
        ),
    ]
