# Generated by Django 2.1.8 on 2019-05-05 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20190505_2153'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lastvisit',
            table='poll_lastvisit',
        ),
        migrations.AlterModelTable(
            name='multiplechoicequestion',
            table='poll_multiplechoicequestion',
        ),
        migrations.AlterModelTable(
            name='multiplechoicequestionanswer',
            table='poll_multiplechoicequestionanswer',
        ),
        migrations.AlterModelTable(
            name='multiplechoicequestionordering',
            table='poll_multiplechoicequestionordering',
        ),
        migrations.AlterModelTable(
            name='openquestion',
            table='poll_openquestion',
        ),
        migrations.AlterModelTable(
            name='openquestionanswer',
            table='poll_openquestionanswer',
        ),
        migrations.AlterModelTable(
            name='openquestionordering',
            table='poll_openquestionordering',
        ),
        migrations.AlterModelTable(
            name='option',
            table='poll_option',
        ),
        migrations.AlterModelTable(
            name='origin',
            table='poll_origin',
        ),
        migrations.AlterModelTable(
            name='poll',
            table='poll_poll',
        ),
        migrations.AlterModelTable(
            name='savedticket',
            table='poll_savedticket',
        ),
        migrations.AlterModelTable(
            name='section',
            table='poll_section',
        ),
        migrations.AlterModelTable(
            name='sectionordering',
            table='poll_sectionordering',
        ),
        migrations.AlterModelTable(
            name='singlechoicequestion',
            table='poll_singlechoicequestion',
        ),
        migrations.AlterModelTable(
            name='singlechoicequestionanswer',
            table='poll_singlechoicequestionanswer',
        ),
        migrations.AlterModelTable(
            name='singlechoicequestionordering',
            table='poll_singlechoicequestionordering',
        ),
        migrations.AlterModelTable(
            name='template',
            table='poll_template',
        ),
        migrations.AlterModelTable(
            name='templatesections',
            table='poll_templatesections',
        ),
    ]
