# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-30 20:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20181229_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tickets', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'sesja oceniania zajęć',
                'verbose_name_plural': 'sesje oceniania zajęć',
            },
        ),
    ]
