# Generated by Django 2.1.8 on 2019-05-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20190505_2205'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lastvisit',
            table='poll_legacy_lastvisit',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_lastvisit_id_seq RENAME TO poll_legacy_lastvisit_id_seq;'),
        migrations.AlterModelTable(
            name='multiplechoicequestion',
            table='poll_legacy_multiplechoicequestion',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_multiplechoicequestion_id_seq RENAME TO poll_legacy_multiplechoicequestion_id_seq;'),
        migrations.RunSQL('ALTER SEQUENCE poll_multiplechoicequestion_options_id_seq RENAME TO poll_legacy_multiplechoicequestion_options_id_seq;'),
        migrations.AlterModelTable(
            name='multiplechoicequestionanswer',
            table='poll_legacy_multiplechoicequestionanswer',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_multiplechoicequestionanswer_id_seq RENAME TO poll_legacy_multiplechoicequestionanswer_id_seq;'),
        migrations.RunSQL('ALTER SEQUENCE poll_multiplechoicequestionanswer_options_id_seq RENAME TO poll_legacy_multiplechoicequestionanswer_options_id_seq;'),
        migrations.AlterModelTable(
            name='multiplechoicequestionordering',
            table='poll_legacy_multiplechoicequestionordering',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_multiplechoicequestionordering_id_seq RENAME TO poll_legacy_multiplechoicequestionordering_id_seq;'),
        migrations.AlterModelTable(
            name='openquestion',
            table='poll_legacy_openquestion',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_openquestion_id_seq RENAME TO poll_legacy_openquestion_id_seq;'),
        migrations.AlterModelTable(
            name='openquestionanswer',
            table='poll_legacy_openquestionanswer',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_openquestionanswer_id_seq RENAME TO poll_legacy_openquestionanswer_id_seq;'),
        migrations.AlterModelTable(
            name='openquestionordering',
            table='poll_legacy_openquestionordering',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_openquestionordering_id_seq RENAME TO poll_legacy_openquestionordering_id_seq;'),
        migrations.AlterModelTable(
            name='option',
            table='poll_legacy_option',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_option_id_seq RENAME TO poll_legacy_option_id_seq;'),
        migrations.AlterModelTable(
            name='origin',
            table='poll_legacy_origin',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_origin_id_seq RENAME TO poll_legacy_origin_id_seq;'),
        migrations.AlterModelTable(
            name='poll',
            table='poll_legacy_poll',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_poll_id_seq RENAME TO poll_legacy_poll_id_seq;'),
        migrations.AlterModelTable(
            name='savedticket',
            table='poll_legacy_savedticket',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_savedticket_id_seq RENAME TO poll_legacy_savedticket_id_seq;'),
        migrations.AlterModelTable(
            name='section',
            table='poll_legacy_section',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_section_id_seq RENAME TO poll_legacy_section_id_seq;'),
        migrations.AlterModelTable(
            name='sectionordering',
            table='poll_legacy_sectionordering',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_sectionordering_id_seq RENAME TO poll_legacy_sectionordering_id_seq;'),
        migrations.AlterModelTable(
            name='singlechoicequestion',
            table='poll_legacy_singlechoicequestion',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_singlechoicequestion_id_seq RENAME TO poll_legacy_singlechoicequestion_id_seq;'),
        migrations.RunSQL('ALTER SEQUENCE poll_singlechoicequestion_options_id_seq RENAME TO poll_legacy_singlechoicequestion_options_id_seq;'),
        migrations.AlterModelTable(
            name='singlechoicequestionanswer',
            table='poll_legacy_singlechoicequestionanswer',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_singlechoicequestionanswer_id_seq RENAME TO poll_legacy_singlechoicequestionanswer_id_seq;'),
        migrations.AlterModelTable(
            name='singlechoicequestionordering',
            table='poll_legacy_singlechoicequestionordering',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_singlechoicequestionordering_id_seq RENAME TO poll_legacy_singlechoicequestionordering_id_seq;'),
        migrations.RunSQL('ALTER SEQUENCE poll_singlechoicequestionordering_hide_on_id_seq RENAME TO poll_legacy_singlechoicequestionordering_hide_on_id_seq;'),
        migrations.AlterModelTable(
            name='template',
            table='poll_legacy_template',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_template_id_seq RENAME TO poll_legacy_template_id_seq;'),
        migrations.AlterModelTable(
            name='templatesections',
            table='poll_legacy_templatesections',
        ),
        migrations.RunSQL('ALTER SEQUENCE poll_templatesections_id_seq RENAME TO poll_legacy_templatesection_id_seq;'),
    ]
