# Generated by Django 2.1.8 on 2019-05-05 23:24

import apps.grade.poll.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_courseinformation'),
        ('poll', '0008_auto_20190505_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Group')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Semester')),
            ],
            options={
                'verbose_name': 'ankieta',
                'verbose_name_plural': 'ankiety',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('poll_type', models.CharField(choices=[(apps.grade.poll.models.PollType(1), 'ankieta dla wykładu'), (apps.grade.poll.models.PollType(2), 'ankieta dla ćwiczeń'), (apps.grade.poll.models.PollType(3), 'ankieta dla pracowni'), (apps.grade.poll.models.PollType(5), 'ankieta dla ćwiczenio-pracowni'), (apps.grade.poll.models.PollType(6), 'ankieta dla seminarium'), (apps.grade.poll.models.PollType(7), 'ankieta dla lektoratu'), (apps.grade.poll.models.PollType(8), 'ankieta dla zajęć wf'), (apps.grade.poll.models.PollType(9), 'ankieta dla repetytorium'), (apps.grade.poll.models.PollType(10), 'ankieta dla projektu'), (apps.grade.poll.models.PollType(1000), 'ankieta dla egzaminu'), (apps.grade.poll.models.PollType(1001), 'ankieta ogólna')], max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('ticket', models.TextField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poll.Schema')),
            ],
        ),
    ]
