# Generated by Django 2.1.8 on 2019-05-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("poll", "0009_auto_20190505_2324")]

    operations = [
        migrations.AlterModelOptions(
            name="schema",
            options={"verbose_name": "szablon", "verbose_name_plural": "szablony"},
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={"verbose_name": "złoszenie", "verbose_name_plural": "zgłoszenia"},
        ),
        migrations.AddField(
            model_name="submission",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
    ]
