# Generated by Django 2.1.8 on 2019-05-10 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("poll", "0010_auto_20190510_2141")]

    operations = [
        migrations.RenameField(
            model_name="schema", old_name="poll_type", new_name="type"
        ),
        migrations.AddField(
            model_name="submission",
            name="poll",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="poll.Poll",
            ),
        ),
    ]
