# Generated by Django 2.0.8 on 2018-12-14 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_create_external_contractors_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesesSystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_required_votes', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'ustawienia systemu prac dyplomowych',
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('kind', models.SmallIntegerField(choices=[(0, 'mgr'), (1, 'inż'), (2, 'lic'), (3, 'lic+inż'), (4, 'isim')])),
                ('status', models.SmallIntegerField(choices=[(1, 'poddana pod głosowanie'), (2, 'zwrócona do poprawek'), (3, 'zaakceptowana'), (4, 'w realizacji'), (5, 'obroniona')])),
                ('reserved', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thesis_advisor', to='users.Employee')),
                ('auxiliary_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thesis_auxiliary_advisor', to='users.Employee')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thesis_student', to='users.Student')),
                ('student_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thesis_student_2', to='users.Student')),
            ],
            options={
                'verbose_name': 'praca dyplomowa',
                'verbose_name_plural': 'prace dyplomowe',
            },
        ),
        migrations.CreateModel(
            name='ThesisVoteBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'brak głosu'), (2, 'odrzucona'), (3, 'zaakceptowana'), (4, 'brak użytkownika')])),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='theses.Thesis')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thesis_votes', to='users.Employee')),
            ],
        ),
    ]
