# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-17 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0002_auto_20180708_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thesis',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'poddana pod głosowanie'), (2, 'zwrócona do poprawek'), (3, 'zaakceptowana'), (4, 'w realizacji'), (5, 'obroniona')]),
        ),
    ]
