# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-11 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_auto_20180717_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThesesCommissionMember',
            new_name='ThesesBoardMember',
        ),
    ]
