# Generated by Django 2.0.8 on 2018-11-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0004_auto_20180811_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesesboardmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Employee'),
        ),
        migrations.AlterField(
            model_name='thesisvotebinding',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Employee'),
        ),
    ]
