# Generated by Django 2.0.8 on 2018-11-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0005_auto_20181121_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
