# Generated by Django 2.0.8 on 2018-12-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0006_auto_20181130_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesesboardmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Employee', verbose_name='Pracownik'),
        ),
    ]
