# Generated by Django 2.0.8 on 2018-12-09 12:57

import apps.theses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0008_auto_20181209_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesessystemsettings',
            options={'verbose_name': 'ustawienia systemu prac dyplomowych', 'verbose_name_plural': 'ustawienia systemu prac dyplomowych'},
        ),
        migrations.AlterField(
            model_name='thesessystemsettings',
            name='num_required_votes',
            field=models.SmallIntegerField(validators=[apps.theses.validators.validate_num_required_votes], verbose_name='Liczba głosów wymaganych do zaakceptowania'),
        ),
    ]
