# Generated by Django 2.0.8 on 2018-12-13 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0009_auto_20181209_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesisvotebinding',
            old_name='vote',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='thesisvotebinding',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='theses.Thesis'),
        ),
        migrations.AlterField(
            model_name='thesisvotebinding',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thesis_votes', to='users.Employee'),
        ),
    ]
