# Generated by Django 2.0.8 on 2018-12-13 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0010_auto_20181213_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesesboardmember',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.Employee', verbose_name='Pracownik'),
        ),
    ]
