# Generated by Django 2.0.8 on 2018-12-13 22:56

from django.db import migrations
from django.contrib.auth.models import Group
from ..users import THESIS_BOARD_MEMBER_GROUP_NAME


def create_group(apps, schema_editor):
    Group.objects.create(name=THESIS_BOARD_MEMBER_GROUP_NAME)


def remove_group(apps, schema_editor):
    Group.objects.filter(name=THESIS_BOARD_MEMBER_GROUP_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0009_auto_20181209_1257'),
    ]

    operations = [
        migrations.RunPython(create_group, remove_group)
    ]
