# Generated by Django 2.0.8 on 2018-12-13 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0012_create_theses_board_member_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesesboardmember',
            name='member',
        ),
        migrations.DeleteModel(
            name='ThesesBoardMember',
        ),
    ]
