# Generated by Django 2.0.8 on 2019-02-07 15:53

import apps.offer.vote.models.system_state
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('vote', '0001_initial'), ('vote', '0002_auto_20180525_0559'), ('vote', '0003_auto_20190206_2240'), ('vote', '0004_auto_20190206_2250'), ('vote', '0005_auto_20190207_0039'), ('vote', '0006_auto_20190207_1454')]

    initial = True

    dependencies = [
        ('users', '0002_auto_20170529_1617'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(0, b'0'), (1, b'1'), (2, b'2'), (3, b'3')], default=0, verbose_name=b'punkty')),
                ('correction', models.IntegerField(choices=[(0, b'0'), (1, b'1'), (2, b'2'), (3, b'3')], default=0, verbose_name=b'korekta')),
                ('free_vote', models.BooleanField(default=False, verbose_name='Głos nie liczy się do limitu')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseEntity', verbose_name=b'podstawa')),
            ],
            options={
                'ordering': ('student', 'entity', '-value'),
                'verbose_name': 'pojedynczy głos',
                'verbose_name_plural': 'pojedyncze głosy',
            },
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=apps.offer.vote.models.system_state.SystemState.get_default_year, max_length=7, verbose_name='rok akademicki')),
                ('max_points', models.IntegerField(default=50, verbose_name='Maksimum punktów na przedmioty')),
                ('max_vote', models.IntegerField(default=3, verbose_name='Maksymalna wartość głosu')),
                ('vote_beg', models.DateField(default=apps.offer.vote.models.system_state.SystemState.get_default_vote_beg, null=True, verbose_name='Początek głosowania')),
                ('vote_end', models.DateField(default=apps.offer.vote.models.system_state.SystemState.get_default_vote_end, null=True, verbose_name='Koniec głosowania')),
                ('winter_correction_beg', models.DateField(default=apps.offer.vote.models.system_state.SystemState.get_default_correction_beg, verbose_name='Początek korekty zimowej')),
                ('winter_correction_end', models.DateField(default=apps.offer.vote.models.system_state.SystemState.get_default_correction_end, verbose_name='Koniec korekty zimowej')),
                ('summer_correction_beg', models.DateField(default=apps.offer.vote.models.system_state.SystemState.get_default_correction_beg, verbose_name='Początek korekty letniej')),
                ('summer_correction_end', models.DateField(default=apps.offer.vote.models.system_state.SystemState.get_default_correction_end, verbose_name='Koniec korekty letniej')),
                ('semester_summer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summer_votes', to='courses.Semester', verbose_name='Semestr letni')),
                ('semester_winter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winter_votes', to='courses.Semester', verbose_name='Semestr zimowy')),
            ],
            options={
                'verbose_name': 'ustawienia głosowania',
                'verbose_name_plural': 'ustawienia głosowań',
            },
        ),
        migrations.AddField(
            model_name='singlevote',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.SystemState', verbose_name=b'ustawienia g\xc5\x82osowania'),
        ),
        migrations.AddField(
            model_name='singlevote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name=b'g\xc5\x82osuj\xc4\x85cy'),
        ),
        migrations.AlterField(
            model_name='singlevote',
            name='correction',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='korekta'),
        ),
        migrations.AlterField(
            model_name='singlevote',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseEntity', verbose_name='podstawa'),
        ),
        migrations.AlterUniqueTogether(
            name='singlevote',
            unique_together={('course', 'state', 'student')},
        ),
        migrations.AlterField(
            model_name='singlevote',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.SystemState', verbose_name='ustawienia głosowania'),
        ),
        migrations.AlterField(
            model_name='singlevote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='głosujący'),
        ),
        migrations.AlterField(
            model_name='singlevote',
            name='value',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='punkty'),
        ),
    ]
