# Generated by Django 2.0.8 on 2019-02-11 14:18

import apps.offer.vote.models.system_state
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20180525_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstate',
            name='summer_correction_beg',
            field=models.DateField(default=None, null=True, verbose_name='Początek korekty letniej'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='summer_correction_end',
            field=models.DateField(default=None, null=True, verbose_name='Koniec korekty letniej'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='vote_beg',
            field=models.DateField(default=None, null=True, verbose_name='Początek głosowania'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='vote_end',
            field=models.DateField(default=None, null=True, verbose_name='Koniec głosowania'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='winter_correction_beg',
            field=models.DateField(default=None, null=True, verbose_name='Początek korekty zimowej'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='winter_correction_end',
            field=models.DateField(default=None, null=True, verbose_name='Koniec korekty zimowej'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='year',
            field=models.CharField(default=apps.offer.vote.models.system_state.SystemState.get_default_year, max_length=7, verbose_name='rok akademicki'),
        ),
    ]
