# Generated by Django 2.0.8 on 2019-04-14 11:47

import apps.offer.vote.models.system_state
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_proposal'),
        ('users', '0015_merge_20190321_1311'),
        ('vote', '0002_auto_20180525_0559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlevote',
            options={'ordering': ('student', 'proposal', '-value'), 'verbose_name': 'pojedynczy głos', 'verbose_name_plural': 'pojedyncze głosy'},
        ),
        migrations.AlterUniqueTogether(
            name='singlevote',
            unique_together={},
        ),
        migrations.RemoveField(
            model_name='systemstate',
            name='max_points',
        ),
        migrations.RemoveField(
            model_name='systemstate',
            name='max_vote',
        ),
        migrations.AddField(
            model_name='singlevote',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposal.Proposal', verbose_name='propozycja'),
        ),
        migrations.AlterField(
            model_name='singlevote',
            name='correction',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='punkty przyznane w korekcie'),
        ),
        migrations.AlterField(
            model_name='singlevote',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.SystemState', verbose_name='Rok akademicki'),
        ),
        migrations.AlterField(
            model_name='singlevote',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='przyznane punkty'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='semester_summer',
            field=models.ForeignKey(blank=True, default=apps.offer.vote.models.system_state._get_default_summer_semester, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.Semester', verbose_name='Semestr letni'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='semester_winter',
            field=models.ForeignKey(blank=True, default=apps.offer.vote.models.system_state._get_default_winter_semester, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.Semester', verbose_name='Semestr zimowy'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='summer_correction_beg',
            field=models.DateField(blank=True, null=True, verbose_name='Początek korekty na semestr letni'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='summer_correction_end',
            field=models.DateField(blank=True, null=True, verbose_name='Koniec korekty na semestr letni'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='vote_beg',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Początek głosowania'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='vote_end',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Koniec głosowania'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='winter_correction_beg',
            field=models.DateField(blank=True, null=True, verbose_name='Początek korekty na semestr zimowy'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='winter_correction_end',
            field=models.DateField(blank=True, null=True, verbose_name='Koniec korekty na semestr zimowy'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='year',
            field=models.CharField(default=apps.offer.vote.models.system_state._get_default_year, max_length=7, validators=[apps.offer.vote.models.system_state._validate_year_format], verbose_name='Rok akademicki'),
        ),
        migrations.RemoveField(
            model_name='singlevote',
            name='course',
        ),
        migrations.RemoveField(
            model_name='singlevote',
            name='free_vote',
        ),
        migrations.AlterUniqueTogether(
            name='singlevote',
            unique_together={('proposal', 'state', 'student')},
        ),
    ]
