# Generated by Django 2.0.8 on 2019-02-07 00:39

import apps.offer.vote.models.system_state
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20190206_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstate',
            name='summer_correction_beg',
            field=models.DateField(default=apps.offer.vote.models.system_state.SystemState.get_default_correction_beg, verbose_name='Początek korekty letniej'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='summer_correction_end',
            field=models.DateField(default=apps.offer.vote.models.system_state.SystemState.get_default_correction_end, verbose_name='Koniec korekty letniej'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='vote_beg',
            field=models.DateField(default=apps.offer.vote.models.system_state.SystemState.get_default_vote_beg, verbose_name='Początek głosowania'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='vote_end',
            field=models.DateField(default=apps.offer.vote.models.system_state.SystemState.get_default_vote_end, verbose_name='Koniec głosowania'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='winter_correction_beg',
            field=models.DateField(default=apps.offer.vote.models.system_state.SystemState.get_default_correction_beg, verbose_name='Początek korekty zimowej'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='winter_correction_end',
            field=models.DateField(default=apps.offer.vote.models.system_state.SystemState.get_default_correction_end, verbose_name='Koniec korekty zimowej'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='year',
            field=models.CharField(default=apps.offer.vote.models.system_state.SystemState.get_default_year, max_length=7, verbose_name='rok akademicki'),
        ),
    ]
