# Generated by Django 2.1.8 on 2019-05-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlevote',
            name='entity',
        ),
    ]
