# Generated by Django 2.1.8 on 2019-08-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_remove_singlevote_entity'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''DELETE FROM vote_singlevote WHERE proposal_id IS NULL;''',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='singlevote',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Proposal', verbose_name='propozycja'),
        ),
    ]
