# Generated by Django 2.0.8 on 2019-02-07 14:54

import apps.offer.vote.models.system_state
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20190207_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstate',
            name='vote_beg',
            field=models.DateField(default=apps.offer.vote.models.system_state.SystemState.get_default_vote_beg, null=True, verbose_name='Początek głosowania'),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='vote_end',
            field=models.DateField(default=apps.offer.vote.models.system_state.SystemState.get_default_vote_end, null=True, verbose_name='Koniec głosowania'),
        ),
    ]
