# Generated by Django 2.0.8 on 2018-12-30 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_to_group', models.BooleanField(default=True, verbose_name='Dodano do grupy')),
                ('add_new_group', models.BooleanField(default=True, verbose_name='Dodano nową grupe')),
                ('classroom_change', models.BooleanField(default=True, verbose_name='Zmieniono sale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
        ),
    ]
