# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferences',
            name='type',
            field=models.CharField(choices=[('send-news', 'Dodano nowy news'), ('enrollment-limit', 'Podniesiono limit ECTS'), ('vote-start', 'Rozpoczęło się głosowanie'), ('grade-start', 'Rozpoczęła się ocena')], max_length=50, verbose_name='typ'),
        ),
    ]
