# Generated by Django 2.0.8 on 2019-01-25 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_auto_20180525_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferencesStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulled_from_queue', models.BooleanField(default=True, verbose_name='Dodano do grupy')),
                ('added_new_group', models.BooleanField(default=True, verbose_name='Dodano nową grupe')),
                ('teacher_has_been_changed', models.BooleanField(default=True, verbose_name='Prowadzący zmieniony')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreferencesTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to_new_group_as_teacher', models.BooleanField(default=True, verbose_name='Przydzielono do grupy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
        ),
        migrations.RemoveField(
            model_name='notificationpreferences',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotificationPreferences',
        ),
    ]
