# Generated by Django 2.1.9 on 2019-06-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190125_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreferencesstudent',
            name='teacher_has_been_changed',
        ),
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='news_has_been_added',
            field=models.BooleanField(default=True, verbose_name='Nowa wiadomość w Aktualnościach'),
        ),
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='not_pulled_from_queue',
            field=models.BooleanField(default=True, verbose_name='Niepowodzenie wciągnięcia Cię do grupy'),
        ),
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='teacher_has_been_changed_enrolled',
            field=models.BooleanField(default=True, verbose_name='Zmiana prowadzącego grupy, do której jesteś zapisany/a'),
        ),
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='teacher_has_been_changed_queued',
            field=models.BooleanField(default=True, verbose_name='Zmiana prowadzącego grupy, do której czekasz w kolejce'),
        ),
        migrations.AddField(
            model_name='notificationpreferencesteacher',
            name='news_has_been_added',
            field=models.BooleanField(default=True, verbose_name='Nowa wiadomość w Aktualnościach'),
        ),
        migrations.AlterField(
            model_name='notificationpreferencesstudent',
            name='added_new_group',
            field=models.BooleanField(default=True, verbose_name='Dodanie nowej grupy przedmiotu, na który jesteś zapisany/a'),
        ),
        migrations.AlterField(
            model_name='notificationpreferencesstudent',
            name='pulled_from_queue',
            field=models.BooleanField(default=True, verbose_name='Zapisanie Cię do grupy'),
        ),
        migrations.AlterField(
            model_name='notificationpreferencesteacher',
            name='assigned_to_new_group_as_teacher',
            field=models.BooleanField(default=True, verbose_name='Przydzielenie do grupy'),
        ),
    ]
