# Generated by Django 2.0.8 on 2019-01-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190125_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='not_pulled_from_queue',
            field=models.BooleanField(default=True, verbose_name='Nie wciągnięto do grupy'),
        ),
    ]
