# Generated by Django 2.1.8 on 2019-09-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20190628_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferencesstudent',
            name='added_new_group',
            field=models.BooleanField(default=False, verbose_name='Dodanie nowej grupy przedmiotu, na który jesteś zapisany/a'),
        ),
        migrations.AlterField(
            model_name='notificationpreferencesstudent',
            name='not_pulled_from_queue',
            field=models.BooleanField(default=False, verbose_name='Niepowodzenie wciągnięcia Cię do grupy'),
        ),
        migrations.AlterField(
            model_name='notificationpreferencesstudent',
            name='pulled_from_queue',
            field=models.BooleanField(default=False, verbose_name='Zapisanie Cię do grupy'),
        ),
    ]
