# Generated by Django 2.0.8 on 2019-02-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationpreferencesstudent_not_pulled_from_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreferencesstudent',
            name='added_new_group',
            field=models.BooleanField(default=True, verbose_name='Dodanie nowej grupy przedmiotu, na który jesteś zapisany'),
        ),
        migrations.AlterField(
            model_name='notificationpreferencesstudent',
            name='not_pulled_from_queue',
            field=models.BooleanField(default=True, verbose_name='Anulowanie wciągnięcia do grupy'),
        ),
        migrations.AlterField(
            model_name='notificationpreferencesstudent',
            name='pulled_from_queue',
            field=models.BooleanField(default=True, verbose_name='Wciągnięcie do grupy'),
        ),
        migrations.AlterField(
            model_name='notificationpreferencesstudent',
            name='teacher_has_been_changed',
            field=models.BooleanField(default=True, verbose_name='Zmiana prowadzącego grupy z przedmiotu, na który jesteś zapisany'),
        ),
        migrations.AlterField(
            model_name='notificationpreferencesteacher',
            name='assigned_to_new_group_as_teacher',
            field=models.BooleanField(default=True, verbose_name='Przydzielenie do grupy'),
        ),
    ]
