# Generated by Django 2.0.8 on 2019-03-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20190205_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferencesstudent',
            name='news_has_been_added',
            field=models.BooleanField(default=True, verbose_name='Powiadomienie o nowej wiadomości w Aktualnościach'),
        ),
    ]
