# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-24 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_auto_20171216_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermSyncData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduler_id', models.PositiveIntegerField(null=True, unique=True, verbose_name='id grupy w schedulerze')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Term', verbose_name='termin')),
            ],
            options={
                'verbose_name': 'Obiekt synchronizacji termin\xf3w grup',
                'verbose_name_plural': 'Obiekty synchronizacji termin\xf3w grup',
            },
        ),
    ]
