# Generated by Django 1.10.8 on 2018-02-01 22:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulersync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsyncdata',
            name='scheduler_id',
            field=models.PositiveIntegerField(null=True, verbose_name='id grupy w schedulerze'),
        ),
    ]
