# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 05:59
from __future__ import unicode_literals

import apps.enrollment.records.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20170529_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Czas ostatniej zmiany'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Group', verbose_name='grupa'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='priorytet'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='users.Student', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Czas dołączenia do kolejki'),
        ),
        migrations.AlterField(
            model_name='record',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='utworzono'),
        ),
        migrations.AlterField(
            model_name='record',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='zmieniano'),
        ),
        migrations.AlterField(
            model_name='record',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Group', verbose_name='grupa'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('0', 'usunięty'), ('1', 'zapisany'), ('2', 'przypięty')], max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='record',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='users.Student', verbose_name='student'),
        ),
    ]
