# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-04 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def translate_status(apps, schema_editor):
    Record = apps.get_model('records', 'Record')
    Queue = apps.get_model('records', 'Queue')

    db_alias = schema_editor.connection.alias

    Record.objects.using(db_alias).filter(old_status='0').update(status='2')  # REMOVED
    Record.objects.using(db_alias).filter(old_status='1').update(status='1')  # ENROLLED
    Record.objects.using(db_alias).filter(old_status='2').delete()

    new_records = []
    for q in Queue.objects.using(db_alias).all():
        record = Record(student_id=q.student_id, group_id=q.group_id, created=q.time, modified=q.edited)
        if q.deleted:
            record.status = '2' # REMOVED
        else:
            record.status = '0' # QUEUED
        new_records.append(record)
    Record.objects.using(db_alias).bulk_create(new_records)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180804_2031'),
        ('courses', '0010_auto_20180804_2031'),
        ('records', '0003_auto_20180525_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOpeningTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
        ),
        migrations.CreateModel(
            name='T0Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
        ),
        migrations.AlterModelOptions(
            name='record',
            options={},
        ),
        migrations.RenameField(
            model_name='record',
            old_name='edited',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='record',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='record',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.RenameField(
            model_name='record',
            old_name='status',
            new_name='old_status',
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('0', 'QUEUED'), ('1', 'ENROLLED'), ('2', 'REMOVED')], default=0, max_length=1, verbose_name='status'),
        ),
        migrations.RunPython(translate_status),
    ]
