# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-04 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_auto_20180804_2031'),
        ('courses', '0010_auto_20180804_2031'),
        ('records', '0004_auto_20180804_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='old_status',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='group',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='student',
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
        migrations.AddIndex(
            model_name='t0times',
            index=models.Index(fields=['student', 'semester'], name='records_t0t_student_da83e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='t0times',
            unique_together=set([('student', 'semester')]),
        ),
        migrations.AddIndex(
            model_name='groupopeningtimes',
            index=models.Index(fields=['student', 'group'], name='records_gro_student_1106ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupopeningtimes',
            unique_together=set([('student', 'group')]),
        ),
    ]