# Generated by Django 2.0 on 2018-08-13 22:43

import apps.enrollment.records.models.records
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20180805_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[(apps.enrollment.records.models.records.RecordStatus('0'), 'Queued'), (apps.enrollment.records.models.records.RecordStatus('1'), 'Enrolled'), (apps.enrollment.records.models.records.RecordStatus('2'), 'Removed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
    ]
