# Generated by Django 2.0.8 on 2018-12-08 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20180813_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='priority',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='priorytet'),
        ),
    ]
