# Generated by Django 2.0.8 on 2019-01-08 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180804_2031'),
        ('courses', '0010_auto_20180804_2031'),
        ('records', '0007_record_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramGroupRestrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Group')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Program')),
            ],
        ),
    ]
