# Generated by Django 2.1.9 on 2019-08-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20190109_1236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programgrouprestrictions',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='programgrouprestrictions',
            name='group',
        ),
        migrations.RemoveField(
            model_name='programgrouprestrictions',
            name='program',
        ),
        migrations.DeleteModel(
            name='ProgramGroupRestrictions',
        ),
    ]
