- name: Add New Relic APT Key
  apt_key:
    id: A758B3FBCD43BE8D123A3476BB29EE038ECCE87C
    url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
    state: present

- name: Add New Relic APT Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt bionic main
    state: present
    filename: newrelic

- name: Add licence key to New Relic agent configuration
  template:
    src: templates/newrelic-infra.yml.j2
    dest: /etc/newrelic-infra.yml

- name: Install the New Relic Agent
  apt:
    pkg: newrelic-infra

- name: Add logs configuration to New Relic.
  template:
    src: templates/newrelic-server-logs.yml.j2
    dest: /etc/newrelic-infra/logging.d/server-logs.yml

- name: Reload the New Relic Agent as there may be a new configuration
  service:
    name: newrelic-infra
    state: restarted
