# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20170529_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='pracownik'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='ukryte'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='lab',
            field=models.IntegerField(blank=True, choices=[(3, 'Chętnie'), (2, 'Być może'), (1, 'Raczej nie'), (0, 'Nie')], null=True, verbose_name='pracownia'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='lecture',
            field=models.IntegerField(blank=True, choices=[(3, 'Chętnie'), (2, 'Być może'), (1, 'Raczej nie'), (0, 'Nie')], null=True, verbose_name='wykład'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseEntity', verbose_name='propozycja'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='review_lecture',
            field=models.IntegerField(blank=True, choices=[(3, 'Chętnie'), (2, 'Być może'), (1, 'Raczej nie'), (0, 'Nie')], null=True, verbose_name='repetytorium'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='seminar',
            field=models.IntegerField(blank=True, choices=[(3, 'Chętnie'), (2, 'Być może'), (1, 'Raczej nie'), (0, 'Nie')], null=True, verbose_name='seminarium'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='tutorial',
            field=models.IntegerField(blank=True, choices=[(3, 'Chętnie'), (2, 'Być może'), (1, 'Raczej nie'), (0, 'Nie')], null=True, verbose_name='ćwiczenia'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='tutorial_lab',
            field=models.IntegerField(blank=True, choices=[(3, 'Chętnie'), (2, 'Być może'), (1, 'Raczej nie'), (0, 'Nie')], null=True, verbose_name='ćwiczenio-pracownia'),
        ),
    ]
