# Generated by Django 2.1.8 on 2019-05-11 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_proposal'),
        ('users', '0015_merge_20190321_1311'),
        ('preferences', '0004_remove_preference_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferencesQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('1', 'wykład'), ('2', 'ćwiczenia'), ('3', 'pracownia'), ('5', 'ćwiczenio-pracownia'), ('6', 'seminarium'), ('7', 'lektorat'), ('8', 'WF'), ('9', 'repetytorium'), ('10', 'projekt')], max_length=2, verbose_name='typ zajęć')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.Proposal', verbose_name='przedmiot')),
            ],
            options={
                'verbose_name': 'pytanie',
                'verbose_name_plural': 'pytania',
                'ordering': ['proposal'],
            },
        ),
        migrations.DeleteModel('Preference'),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Employee', verbose_name='pracownik')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.PreferencesQuestion', verbose_name='pytanie')),
                ('answer', models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Chętnie'), (2, 'Być może'), (1, 'Raczej nie'), (0, 'Nie')], null=True, verbose_name='wola')),
            ],
            options={
                'verbose_name': 'preferencja pracownika',
                'verbose_name_plural': 'preferencje pracowników'
            },
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('employee', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='preferencesquestion',
            unique_together={('proposal', 'class_type')},
        ),
    ]
