# Generated by Django 2.1.8 on 2019-08-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0005_auto_20190511_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencesquestion',
            name='class_type',
            field=models.CharField(choices=[('1', 'wykład'), ('2', 'ćwiczenia'), ('3', 'pracownia'), ('5', 'ćwiczenio-pracownia'), ('6', 'seminarium'), ('7', 'lektorat'), ('8', 'WF'), ('9', 'repetytorium'), ('10', 'projekt'), ('11', 'tutoring'), ('12', 'proseminarium')], max_length=2, verbose_name='typ zajęć'),
        ),
    ]
