# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_auto_20170606_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='contents',
            field=models.TextField(blank=True, default='', verbose_name='Treści programowe'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='effects_codes',
            field=models.TextField(blank=True, default='', help_text='Wypełnia DDD', verbose_name='Symbole kierunkowych efektów kształcenia'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='effects_txt',
            field=models.TextField(blank=True, default='', verbose_name='Zakładane efekty kształcenia'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='courses.CourseEntity', verbose_name='podstawa przedmiotu'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='exam_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='egzamin'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='literature',
            field=models.TextField(blank=True, default='', verbose_name='Zalecana literatura (podręczniki)'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='objectives',
            field=models.TextField(blank=True, default='', verbose_name='Cele przedmiotu'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='passing_form',
            field=models.TextField(blank=True, default='', verbose_name='Forma zaliczenia poszczególnych komponentów przedmiotu/modułu, sposób sprawdzenia osiągnięcia zamierzonych efektów kształcenia'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='project_presentation_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='prezentacja projektu'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='requirements',
            field=models.TextField(blank=True, default='', verbose_name='Wymagania wstępne w zakresie wiedzy, umiejętności i kompetencji społecznych'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='studies_type',
            field=models.CharField(choices=[('isim', 'isim'), ('inf', 'informatyka'), ('both', 'informatyka, ISIM')], default='both', max_length=80, verbose_name='Kierunek studiów'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='tests_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='sprawdziany/kolokwia'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Rok studiów'),
        ),
    ]
