# Generated by Django 2.1.8 on 2019-05-12 22:12

import apps.offer.proposal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='smtr',
            field=models.CharField(choices=[(apps.offer.proposal.models.SemesterChoices('u'), 'nieokreślony'), (apps.offer.proposal.models.SemesterChoices('z'), 'zimowy'), (apps.offer.proposal.models.SemesterChoices('l'), 'letni')], default=apps.offer.proposal.models.SemesterChoices('u'), max_length=1, verbose_name='semestr'),
        ),
        migrations.RunSQL(
            '''UPDATE proposal_proposal
            SET smtr=courses_courseinformation.semester
            FROM courses_courseinformation
            WHERE proposal_proposal.courseinformation_ptr_id=courses_courseinformation.id;
            ''',
        ),
    ]
