# Generated by Django 2.1.8 on 2019-05-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0007_proposal_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentwork',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='learning_methods',
        ),
        migrations.DeleteModel(
            name='LearningMethod',
        ),
        migrations.DeleteModel(
            name='StudentWork',
        ),
        migrations.DeleteModel(
            name='Syllabus',
        ),
    ]
