from proposal import Proposal
from proposal_description import ProposalDescription
from proposal_tag import ProposalTag
from proposal_description_tag import ProposalDescriptionTag
from book import Book
