# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-25 05:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171019_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='consultations',
            field=models.TextField(blank=True, null=True, verbose_name='konsultacje'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='homepage',
            field=models.URLField(blank=True, default='', null=True, verbose_name='strona domowa'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='receive_mass_mail_enrollment',
            field=models.BooleanField(default=True, verbose_name='otrzymuje mailem ogłoszenia Zapisów'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='receive_mass_mail_grade',
            field=models.BooleanField(default=True, verbose_name='otrzymuje mailem ogłoszenia Oceny Zajęć'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='receive_mass_mail_offer',
            field=models.BooleanField(default=True, verbose_name='otrzymuje mailem ogłoszenia OD'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='pokój'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'aktywny'), (1, 'nieaktywny')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='tytuł naukowy'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='czy pracownik?'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='czy student?'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='is_zamawiany',
            field=models.BooleanField(default=False, verbose_name='czy zamawiany?'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='type_of_points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.PointTypes', verbose_name='rodzaj punktów'),
        ),
        migrations.AlterField(
            model_name='student',
            name='block',
            field=models.BooleanField(default=False, verbose_name='blokada planu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ects',
            field=models.PositiveIntegerField(default=0, verbose_name='punkty ECTS'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricula',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Numer indeksu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Program', verbose_name='Program Studiów'),
        ),
        migrations.AlterField(
            model_name='student',
            name='receive_mass_mail_enrollment',
            field=models.BooleanField(default=True, verbose_name='otrzymuje mailem ogłoszenia Zapisów'),
        ),
        migrations.AlterField(
            model_name='student',
            name='receive_mass_mail_grade',
            field=models.BooleanField(default=True, verbose_name='otrzymuje mailem ogłoszenia Oceny Zajęć'),
        ),
        migrations.AlterField(
            model_name='student',
            name='receive_mass_mail_offer',
            field=models.BooleanField(default=True, verbose_name='otrzymuje mailem ogłoszenia OD'),
        ),
        migrations.AlterField(
            model_name='student',
            name='records_opening_bonus_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Przyspieszenie otwarcia zapisów (minuty)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semestr',
            field=models.PositiveIntegerField(default=0, verbose_name='Semestr'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.PositiveIntegerField(default=0, help_text='0 - aktywny student, 1 - skreślony student', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='studiazamawiane',
            name='bank_account',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Numer konta bankowego'),
        ),
        migrations.AlterField(
            model_name='studiazamawiane',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Uwagi'),
        ),
        migrations.AlterField(
            model_name='studiazamawiane',
            name='points',
            field=models.FloatField(blank=True, null=True, verbose_name='Punkty'),
        ),
        migrations.AlterField(
            model_name='studiazamawiane',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zamawiane', to='users.Student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='studiazamawiane2012',
            name='bank_account',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Numer konta bankowego'),
        ),
        migrations.AlterField(
            model_name='studiazamawiane2012',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Uwagi'),
        ),
        migrations.AlterField(
            model_name='studiazamawiane2012',
            name='points',
            field=models.FloatField(blank=True, null=True, verbose_name='Punkty'),
        ),
        migrations.AlterField(
            model_name='studiazamawiane2012',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zamawiane2012', to='users.Student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='czy pracownik?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='czy student?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_zamawiany',
            field=models.BooleanField(default=False, verbose_name='czy zamawiany?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('pl', 'Polish'), ('en', 'English')], default='pl', max_length=5, verbose_name='preferowany język Systemu Zapisów'),
        ),
    ]
