# Generated by Django 1.11.9 on 2018-03-25 22:48
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171019_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='isim',
        ),
    ]
