# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-29 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_student_isim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiazamawiane',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studiazamawiane2012',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudiaZamawianeMaileOpiekunow',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='is_zamawiany',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_zamawiany',
        ),
        migrations.DeleteModel(
            name='StudiaZamawiane',
        ),
        migrations.DeleteModel(
            name='StudiaZamawiane2012',
        ),
    ]
