# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-13 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20170606_1842'),
        ('email_change', '0001_initial'),
        ('notifications', '0001_initial'),
        ('schedule', '0005_auto_20171112_2306'),
        ('news', '0001_initial'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('users', '0007_auto_20180329_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
