# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-01 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_consents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consents',
            new_name='PersonalDataConsent',
        ),
    ]
