# Generated by Django 1.11.9 on 2018-04-20 23:34
from django.db import migrations


def add_respective_users_to_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Employee = apps.get_model("users", "Employee")
    Student = apps.get_model("users", "Student")
    db_alias = schema_editor.connection.alias

    students, created = Group.objects.using(db_alias).get_or_create(name='students')
    employees, created = Group.objects.using(db_alias).get_or_create(name='employees')

    for employee in Employee.objects.using(db_alias).all():
        user = employee.user
        employees.user_set.add(user)

    for student in Student.objects.using(db_alias).all():
        user = student.user
        students.user_set.add(user)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_auto_20180601_1918'),
    ]

    operations = [
        migrations.RunPython(add_respective_users_to_groups, reverse_code=migrations.RunPython.noop),
    ]
