# Generated by Django 1.11.9 on 2018-04-20 23:34
from django.db import migrations
from django.contrib.auth.models import Group
from apps.users.models import Employee, Student


def add_respective_users_to_groups(apps, schema_editor):
    students, created = Group.objects.get_or_create(name='students')
    employees, created = Group.objects.get_or_create(name='employees')

    for employee in Employee.objects.all():
        user = employee.user
        employees.user_set.add(user)

    for student in Student.objects.all():
        user = student.user
        students.user_set.add(user)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_auto_20180601_1918'),
    ]

    operations = [
        migrations.RunPython(add_respective_users_to_groups, reverse_code=migrations.RunPython.noop),
    ]
