# Generated by Django 1.11.9 on 2018-04-20 23:25
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180413_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__last_name', 'user__first_name'], 'permissions': (('mailto_all_students', 'Mo\u017ce wysy\u0142a\u0107 maile do wszystkich student\xf3w'), ('is_employee', 'Is employee')), 'verbose_name': 'pracownik', 'verbose_name_plural': 'Pracownicy'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__last_name', 'user__first_name'], 'permissions': (('is_student', 'Is student'),), 'verbose_name': 'student', 'verbose_name_plural': 'studenci'},
        ),
    ]
