# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-12 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('schedule', '0006_auto_20180525_0559'),
        ('news', '0002_auto_20180525_0559'),
        ('poll', '0005_auto_20180525_0559'),
        ('email_change', '0001_initial'),
        ('users', '0009_auto_20180420_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='studiazamawiane',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studiazamawiane2012',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudiaZamawianeMaileOpiekunow',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='isim',
        ),
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
        migrations.DeleteModel(
            name='StudiaZamawiane',
        ),
        migrations.DeleteModel(
            name='StudiaZamawiane2012',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
