# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-04 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180712_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingtimesview',
            name='course',
        ),
        migrations.RemoveField(
            model_name='openingtimesview',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='openingtimesview',
            name='student',
        ),
        migrations.DeleteModel(
            name='OpeningTimesView',
        ),
    ]
