# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-02 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180420_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__last_name', 'user__first_name'], 'permissions': (('mailto_all_students', 'Może wysyłać maile do wszystkich studentów'),), 'verbose_name': 'pracownik', 'verbose_name_plural': 'Pracownicy'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'student', 'verbose_name_plural': 'studenci'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='consultations',
            field=models.TextField(blank=True, null=True, verbose_name='konsultacje'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='homepage',
            field=models.URLField(blank=True, default='', null=True, verbose_name='strona domowa'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='receive_mass_mail_enrollment',
            field=models.BooleanField(default=True, verbose_name='otrzymuje mailem ogłoszenia Zapisów'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='receive_mass_mail_grade',
            field=models.BooleanField(default=True, verbose_name='otrzymuje mailem ogłoszenia Oceny Zajęć'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='receive_mass_mail_offer',
            field=models.BooleanField(default=True, verbose_name='otrzymuje mailem ogłoszenia OD'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='pokój'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'aktywny'), (1, 'nieaktywny')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='tytuł naukowy'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='type_of_points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.PointTypes', verbose_name='rodzaj punktów'),
        ),
        migrations.AlterField(
            model_name='student',
            name='block',
            field=models.BooleanField(default=False, verbose_name='blokada planu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ects',
            field=models.PositiveIntegerField(default=0, verbose_name='punkty ECTS'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricula',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Numer indeksu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Program', verbose_name='Program Studiów'),
        ),
        migrations.AlterField(
            model_name='student',
            name='receive_mass_mail_enrollment',
            field=models.BooleanField(default=True, verbose_name='otrzymuje mailem ogłoszenia Zapisów'),
        ),
        migrations.AlterField(
            model_name='student',
            name='receive_mass_mail_grade',
            field=models.BooleanField(default=True, verbose_name='otrzymuje mailem ogłoszenia Oceny Zajęć'),
        ),
        migrations.AlterField(
            model_name='student',
            name='receive_mass_mail_offer',
            field=models.BooleanField(default=True, verbose_name='otrzymuje mailem ogłoszenia OD'),
        ),
        migrations.AlterField(
            model_name='student',
            name='records_opening_bonus_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Przyspieszenie otwarcia zapisów (minuty)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semestr',
            field=models.PositiveIntegerField(default=0, verbose_name='Semestr'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.PositiveIntegerField(default=0, help_text='0 - aktywny student, 1 - skreślony student', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
