# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-28 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180602_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDataConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.NullBooleanField(verbose_name='zgoda udzielona')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='users.Student')),
            ],
            options={
                'verbose_name': 'Zgoda na udostępnianie danych osobowych',
                'verbose_name_plural': 'Zgody na udostępnianie danych osobowych',
            },
        ),
    ]
