# Generated by Django 2.0.8 on 2018-12-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_create_external_contractors_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='initials',
            field=models.CharField(blank=True, help_text='Inicjały użytkownika. Jeżeli puste, zostaną wygenerowane wg wzoru: &lt;pierwsza litera imienia&gt; + &lt;dwie pierwsze litery nazwiska&gt;', max_length=20, null=True, verbose_name='inicjały'),
        ),
        migrations.AddField(
            model_name='student',
            name='initials',
            field=models.CharField(blank=True, help_text='Inicjały użytkownika. Jeżeli puste, zostaną wygenerowane wg wzoru: &lt;pierwsza litera imienia&gt; + &lt;dwie pierwsze litery nazwiska&gt;', max_length=20, null=True, verbose_name='inicjały'),
        ),
    ]
