# Generated by Django 2.0.8 on 2019-02-06 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_create_external_contractors_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='consultations',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(4200)], verbose_name='konsultacje'),
        ),
    ]
