# Generated by Django 2.0.8 on 2019-03-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180804_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='usos_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID w USOSie'),
        ),
    ]
