# Generated by Django 2.0.8 on 2019-03-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_employee_usos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='usos_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Kod studenta w systemie USOS'),
        ),
    ]
