# Generated by Django 2.0.8 on 2019-03-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_student_usos_id'),
        ('users', '0012_auto_20190206_2301'),
    ]

    operations = [
    ]
