# Generated by Django 2.1.13 on 2019-10-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_program_type_of_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='receive_mass_mail_enrollment',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='receive_mass_mail_grade',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='receive_mass_mail_offer',
        ),
        migrations.RemoveField(
            model_name='student',
            name='receive_mass_mail_enrollment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='receive_mass_mail_grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='receive_mass_mail_offer',
        ),
    ]
