# Generated by Django 2.1.13 on 2019-12-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20191020_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_news_view',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_news_view',
        ),
    ]
