# Generated by Django 2.1.15 on 2020-03-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200219_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='algorytmy_l',
        ),
        migrations.RemoveField(
            model_name='student',
            name='block',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dyskretna_l',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ects_in_semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='numeryczna_l',
        ),
        migrations.RemoveField(
            model_name='student',
            name='programowanie_l',
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Student może być aktywny lub skreślony.', verbose_name='aktywny'),
        ),
        migrations.RunSQL(sql='''
            UPDATE users_student
            SET is_active = NOT (status::bool)
        '''),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='t0',
        ),
    ]
