# Generated by Django 2.0.8 on 2019-01-12 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20180804_2031'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddIndex(
            model_name='hiddengroups',
            index=models.Index(fields=['group', 'role'], name='timetable_h_group_i_b0d5c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hiddengroups',
            unique_together={('group', 'role')},
        ),
    ]
