# Generated by Django 2.0.8 on 2019-02-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180804_2031'),
        ('courses', '0014_auto_20190212_1313'),
        ('timetable', '0002_auto_20190112_0200'),
    ]

    operations = [
        migrations.RunSQL(
            "DELETE FROM timetable_pin a USING timetable_pin b WHERE a.id < b.id AND a.student_id = b.student_id AND a.group_id = b.group_id;"
        ),
        migrations.AlterUniqueTogether(
            name='pin',
            unique_together={('student', 'group')},
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['student', 'group'], name='timetable_p_student_5e9655_idx'),
        ),
    ]
