# Generated by Django 2.1.9 on 2019-08-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20190215_0909'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hiddengroups',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='hiddengroups',
            name='group',
        ),
        migrations.RemoveField(
            model_name='hiddengroups',
            name='role',
        ),
        migrations.DeleteModel(
            name='HiddenGroups',
        ),
    ]
